export const ADD_PRODUCT_TYPE_TO_CART = "ADD_PRODUCT_TYPE_TO_CART";
export const INCREMENT_CART_ITEM_COUNT = "INCREMENT_CART_ITEM_COUNT";
export const DECREMENT_CART_ITEM_COUNT = "DECREMENT_CART_ITEM_COUNT";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";

export const PAYMENT_LOADING = "PAYMENT_LOADING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

// export const CHECKOUT_LOADING = "CHECKOUT_LOADING";
// export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
// export const CHECKOUT_FAILED = "CHECKOUT_FAILED";

export const RESET_CHECKOUT_ERROR = "RESET_CHECKOUT_ERROR";
