export const GET_ALBUMS_LOADING = "GET_ALBUMS_LOADING";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILED = "GET_ALBUMS_FAILED";

export const CREATE_ALBUM_LOADING = "CREATE_ALBUM_LOADING";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAILED = "CREATE_ALBUM_FAILED";

export const UPDATE_ALBUM_LOADING = "UPDATE_ALBUM_LOADING";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";
export const UPDATE_ALBUM_FAILED = "UPDATE_ALBUM_FAILED";

export const GET_ALBUM_SETTINGS_LOADING = "GET_ALBUM_SETTINGS_LOADING";
export const GET_ALBUM_SETTINGS_SUCCESS = "GET_ALBUM_SETTINGS_SUCCESS";
export const GET_ALBUM_SETTINGS_FAILED = "GET_ALBUM_SETTINGS_FAILED";

export const PRINT_ALBUM_LOADING = "PRINT_ALBUM_LOADING";
export const PRINT_ALBUM_SUCCESS = "PRINT_ALBUM_SUCCESS";
export const PRINT_ALBUM_FAILED = "PRINT_ALBUM_FAILED";
