export const GET_ALBUMS_LOADING = "GET_ALBUMS_LOADING";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILED = "GET_ALBUMS_FAILED";

export const CREATE_ALBUM_LOADING = "CREATE_ALBUM_LOADING";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAILED = "CREATE_ALBUM_FAILED";
